org: sambacha
app: sushi-api
service: exchange

frameworkVersion: '>=1.75.1 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 320 # optional, in MB, default is 1024
  timeout: 20 # optional, in seconds, default is 6
  logRetentionInDays: 1

plugins:
  - serverless-plugin-typescript
  - serverless-api-cloudfront

custom:
  apiCloudFront:
    domain: api.sushilayer.info
    certificate: 'arn:aws:acm:us-east-1:870337023970:certificate/442d57cb-e33e-45d1-b836-5fd0abd57930'
    compress: true
    cookies: none
    headers: none
    querystring: none
    priceClass: PriceClass_100
    minimumProtocolVersion: TLSv1

functions:
  legacy-summary:
    handler: src/legacy/summary.handler
    events:
      - http:
          method: get
          path: /legacy/summary

  legacy-tickers:
    handler: src/legacy/tickers.handler
    events:
      - http:
          method: get
          path: /legacy/tickers

  legacy-assets:
    handler: src/legacy/assets.handler
    events:
      - http:
          method: get
          path: /legacy/assets

  legacy-orderbook:
    handler: src/legacy/orderbook.handler
    events:
      - http:
          method: get
          path: '/legacy/orderbook/{pair}'

  legacy-trades:
    handler: src/legacy/trades.handler
    events:
      - http:
          method: get
          path: '/legacy/trades/{pair}'

  swap-summary:
    handler: src/swap/summary.handler
    events:
      - http:
          method: get
          path: /swap/summary

  swap-tickers:
    handler: src/swap/tickers.handler
    events:
      - http:
          method: get
          path: /swap/tickers

  swap-assets:
    handler: src/swap/assets.handler
    events:
      - http:
          method: get
          path: /swap/assets

  swap-orderbook:
    handler: src/swap/orderbook.handler
    events:
      - http:
          method: get
          path: '/swap/orderbook/{pair}'

  swap-trades:
    handler: src/swap/trades.handler
    events:
      - http:
          method: get
          path: '/swap/trades/{pair}'

  404:
    handler: src/404.handler
    events:
      - http:
          method: get
          path: '/{catchall+}'
